# Generated by Django 5.1.7 on 2026-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='telephone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
