# Generated by Django 5.1.7 on 2026-06-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
