name: Django Docker CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t multi-shop .

      - name: Run Tests
        run: |
          docker run --rm multi-shop python manage.py test